export const IDLE_SPIDER_QUIPS = [
  'IS THAT VIBRATION PREY?',
  'JUST GROOMING MY PEDIPALPS.',
  'EIGHT EYES, ZERO REGRETS.',
  'NICE BREEZE ON MY TRICHOBOTHRIA.',
  'SPINNERETS FEELING SILKY TODAY.',
  'WAITING FOR A JUICY CRICKET…',
  'DID SOMETHING FLUTTER OVER THERE?',
  'CALCULATING THE PERFECT POUNCE…',
  'MY WEBS ARE PURE ART.',
  'MIGHT TAKE A QUICK CEILING NAP.',
  'STRETCHING LEGS 1 THROUGH 8…',
  'FEELING SHARP IN MY EXOSKELETON.',
  'IS IT TASTING AIR OR TASTING DIRT?',
  'SHH… I AM BLENDING IN.',
  'CONTEMPLATING HYDRAULIC LEG POWER.',
  'NEED MORE THREAD FOR THIS CORNER.',
  'TAP TAP… ANY ISOPODS HOME?',
  'REFLEXES MEASURED IN MILLISECONDS.',
  'PERCHED AND PATIENT.',
  'JUST A CUTE LITTLE JUMPING SPIDER.',
];

export function getNextIdleQuip(lastIndex = -1, randomFn = Math.random) {
  let index = Math.floor(randomFn() * IDLE_SPIDER_QUIPS.length);
  if (index === lastIndex) {
    index = (index + 1) % IDLE_SPIDER_QUIPS.length;
  }
  return { index, quip: IDLE_SPIDER_QUIPS[index] };
}

export const HURRY_START_QUIPS = [
  'WAIT, WHAT WAS THAT?!',
  'OOH! A SHADOW!',
  'GOTTA CHECK SOMETHING REAL QUICK!',
  'HEARD A TWITCH OVER THERE!',
  'BRB, INSPECTING A SPEC OF DIRT!',
  'DID I LEAVE SOMETHING OVER HERE?',
  'HOLD ON, SNEAK CHECK!',
  'FALSE ALARM SPRINT GO!',
];

export const HURRY_REALIZE_QUIPS = [
  '…NEVER MIND.',
  'JUST A PIECE OF MOSS.',
  'FALSE ALARM!',
  'NOTHING THERE.',
  'EH, FORGOT WHAT I WAS DOING.',
  'WHOOPS, JUST A SHADOW.',
  'MY BAD. JUST DUST.',
  'ALL CLEAR, BACK TO CHILLING.',
];

